# A workflow to install dependencies, run unit tests, and lint

name: GitHub Actions CI
on:
  pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Setup up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Linting with flake8
        run: |
          flake8 mnist_models/*py --show-source --max-line-length=100 --exit-zero
          flake8 tests/*py --show-source --max-line-length=100 --exit-zero

      - name: Unit tests with pytest
        run: |
          pytest -v
